apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-healing-app
  namespace: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: self-healing-app
  template:
    metadata:
      labels:
        app: self-healing-app
    spec:
      containers:
        - name: self-healing-app
          image: aizenackerman/self-healing-app:0dd0f0934634d0789c332b80617c898f8a3f6441
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "0dd0f0934634d0789c332b80617c898f8a3f6441"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
